// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEecPHBQAzBAMI-ElvX2wFZTMAoBPso4',
    appId: '1:191341556748:web:72e34076829d357bfb6a29',
    messagingSenderId: '191341556748',
    projectId: 'cat-tarot-56be0',
    authDomain: 'cat-tarot-56be0.firebaseapp.com',
    storageBucket: 'cat-tarot-56be0.firebasestorage.app',
    measurementId: 'G-Y2BKDK0FWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnLt6YxxFpeGmPc3Pz0lOYGKbB7SszYw',
    appId: '1:191341556748:android:788cff8340995c52fb6a29',
    messagingSenderId: '191341556748',
    projectId: 'cat-tarot-56be0',
    storageBucket: 'cat-tarot-56be0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhL2t-NXhnskIAKzCFT5KAuKJDyhkgwW8',
    appId: '1:191341556748:ios:2cafe03927270a6ffb6a29',
    messagingSenderId: '191341556748',
    projectId: 'cat-tarot-56be0',
    storageBucket: 'cat-tarot-56be0.firebasestorage.app',
    iosBundleId: 'com.example.tarot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhL2t-NXhnskIAKzCFT5KAuKJDyhkgwW8',
    appId: '1:191341556748:ios:2cafe03927270a6ffb6a29',
    messagingSenderId: '191341556748',
    projectId: 'cat-tarot-56be0',
    storageBucket: 'cat-tarot-56be0.firebasestorage.app',
    iosBundleId: 'com.example.tarot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUEecPHBQAzBAMI-ElvX2wFZTMAoBPso4',
    appId: '1:191341556748:web:5707068f64f87ec9fb6a29',
    messagingSenderId: '191341556748',
    projectId: 'cat-tarot-56be0',
    authDomain: 'cat-tarot-56be0.firebaseapp.com',
    storageBucket: 'cat-tarot-56be0.firebasestorage.app',
    measurementId: 'G-G8TSXGQV3Y',
  );
}
